# Generated by Django 4.2.7 on 2024-04-27 06:18

import django.core.validators
from django.db import migrations, models
import employee.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='Employee_Images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), employee.models.validate_file_size])),
            ],
            options={
                'verbose_name': 'EmployeeMaster',
                'verbose_name_plural': 'EmployeeMaster',
            },
        ),
    ]
